// eslint.config.js
// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
module.exports = {
    env: {
      jest: true,
      node: true
    },
    root: true,
    plugins: [
      "@typescript-eslint",
      "import",
      "@stylistic"
    ],
    parser: "@typescript-eslint/parser",
    parserOptions: {
      ecmaVersion: 2018,
      sourceType: "module",
      project: "./tsconfig.dev.json"
    },
    extends: [
      "plugin:import/typescript"
    ],
    settings: {
      "import/parsers": {
        "@typescript-eslint/parser": [
          ".ts",
          ".tsx"
        ]
      },
      "import/resolver": {
        node: {},
        typescript: {
          project: "./tsconfig.dev.json",
          alwaysTryTypes: true
        }
      }
    },
    ignorePatterns: [
      "*.js",
      "*.d.ts",
      "node_modules/",
      "*.generated.ts"
    ]
  };